language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_script: 
  - npm install gitbook-cli -g

script: 
  - gitbook build
  - cp README.md _book 
# E: Build LifeCycle

deploy:
  provider: pages # deploy to GitHub Pages
  skip_cleanup: true # don't clean generated site
  github_token: $GITHUB_TOKEN # provide the encrypted token
  on:
    branch: master
  local-dir: _book #Directory to push to GitHub Pages, defaults to current directory. Can be specified as an absolute path or a relative path from the current directory.
  keep-history: true
  email: hyram.tang@gmail.com # optional, defaults to "deploy@travis-ci.org"
  name: Hyram # optional, defaults to "Deployment Bot"
