language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_script: 
  - npm install gitbook-cli -g

script: 
  - gitbook build

after_script:
  - cp -r _book/* ./docs/ && rm -rf ./_book
# E: Build LifeCycle